FROM python:3.9-slim

# These two environment variables prevent __pycache__/ files.
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app

COPY ./src ./src
COPY ./pyproject.toml ./pyproject.toml
# hatchling doesn't work with README.md
COPY ./README.md ./README.md

RUN pip install --upgrade pip --no-cache-dir
RUN pip install -e . --no-cache-dir
RUN python -m ecology makemigrations
RUN python -m ecology migrate

ENTRYPOINT python3.9 -m ecology runserver 0.0.0.0:8000 --noreload
EXPOSE 8000
