# A workflow for deploying the Unit Tests coverage report to GitHub Pages
name: Deploy coverage report to Pages

on:
   # Runs on pushes targeting the default branch
   push:
       branches: ['site']

   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
   contents: read
   pages: write
   id-token: write

# Allow one concurrent deployment
concurrency:
   group: 'pages'
   cancel-in-progress: true

jobs:
   # Single deploy job since we're just deploying
   deploy:
       environment:
           name: github-pages
           url: ${{ steps.deployment.outputs.page_url }}
       runs-on: ubuntu-latest
       steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                python-version: "3.10"
            - name: Install Package
              run: python -m pip install -e .[tests]
            - name: Run Tests with saving in html
              env:
                SECRET_KEY: 1kjb16jg15kf1j65hb61j1g
              run: python -m coverage run -m ecology test hackaton && coverage html
            - name: Deploy
              uses: moodiest/push-to-branch-action@develop
              env:
                REPO: self
                BRANCH: gh-pages
                FOLDER: htmlcov
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
